title: Gerob
tagline: Available to hire for web and mobile apps
description: Gerob is a coder, developer available to hire for web and mobile apps. PHP/Laravel, Node.js, Python, and JavaScript. Freelance or full-time. Reach out on LinkedIn or GitHub.
url: https://gerob.github.io
lang: en_US
author:
  name: Gerob
  url: https://github.com/gerob
logo: https://github.com/gerob.png
social:
  name: Gerob
  links:
    - https://github.com/gerob
    - https://www.linkedin.com/in/gerobkimball/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
